version: "3.2"
services:
  front:
    build: ./front
    image: front
    volumes:
      - ./front/build:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - back
  back:
    build: ./back
    image: back
    networks:
      - backnet
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    networks:
      - backnet
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

networks:
  backnet:
    driver: bridge
